spring.application.name=api13-08-2026
spring.datasource.url=jdbc:postgresql://localhost:5432/usuariosdb
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true